name: open.mp server browser

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      
      - '**/README.md'
      - '**/LICENSE'
      - '**/resources_rc.py'
      - '**/version.json'
      - '**/version.txt'
      - 'screenshots/**'
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8.2
        uses: actions/setup-python@v3
        with:
          python-version: "3.8.2"
      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt PyInstaller
      - name: Build with PyInstaller
        run: |
          PyInstaller main.spec
      
      - name: Generate artifact name
        id: vars
        shell: bash
        run: |
          artifact_name="openmp-server-browser-${GITHUB_RUN_ID}"
          echo "artifact_name=${artifact_name}" >> $GITHUB_OUTPUT
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.vars.outputs.artifact_name }}
          path: dist/omp-server-browser.exe
          if-no-files-found: error
      
      - name: Update Nightly Release
        uses: andelf/nightly-release@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: nightly
          name: 'Nightly'
          prerelease: true
          body: 'Nightly release'
          files: |
            ./dist/*.exe
